In [93]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10):my_arr2 = my_arr * 2

CPU times: user 22.4 ms, sys: 8.73 ms, total: 31.1 ms
Wall time: 117 ms


In [11]:
print(my_arr)
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

[     0      1      2 ..., 999997 999998 999999]
CPU times: user 757 ms, sys: 204 ms, total: 961 ms
Wall time: 961 ms


In [13]:
# numpy 的 ndarray:一种多维数组对象
data = np.random.randn(2,3) #生成一个二行三列的随机数组
data

array([[ 0.77582206, -1.11806076,  2.38934168],
       [ 0.83119175, -0.56875796, -0.93168269]])

In [17]:
data*10 #数组运算*10

array([[  7.75822064, -11.18060755,  23.89341676],
       [  8.31191746,  -5.68757961,  -9.31682688]])

In [18]:
data+data #数组加法

array([[ 1.55164413, -2.23612151,  4.77868335],
       [ 1.66238349, -1.13751592, -1.86336538]])

In [20]:
#要经常使用import numpy as np
#这样的话调用函数的时候是写np.min 或者np.max
#不建议使用 from numpy import * 
#为numpy的命名空间很大而使用的时候就直接是max或者min，
#这样容易与Python的内置函数重名（比如min和max）。

In [21]:
data.shape

(2, 3)

In [22]:
data.dtype

dtype('float64')

In [23]:
#容器里面的数据类型必须是相同的，这点和python的list容器不同！！！！

In [32]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(type(data1),type(arr1))

<class 'list'> <class 'numpy.ndarray'>


In [33]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [37]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)

In [40]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
arr2.ndim

2

In [42]:
arr2.shape

(2, 4)

In [43]:
arr1.dtype

dtype('float64')

In [44]:
arr2.dtype

dtype('int64')

In [47]:
print(np.zeros(10))
print(np.zeros((3,6)))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [49]:
np.empty((2,3,2)) #np.empty 并不是返回全0数组，有时候会返回未初始化的垃圾值

array([[[  3.10503618e+231,   4.33563098e-311],
        [  2.96439388e-323,   0.00000000e+000],
        [  0.00000000e+000,   8.60952352e-072]],

       [[  5.95203143e-091,   3.12074118e-033],
        [  4.29181707e-038,   5.78559079e+174],
        [  3.99910963e+252,   8.34402697e-309]]])

In [50]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
# dtype 数据类型是一种特殊对象，ndarrary 将一块内存解释为特定数据类型所需的信息
arr1 = np.array([1, 2, 3],dtype=np.float64)
arr2 = np.array([1, 2, 3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [52]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [53]:
# 可以通过 数组的 astype() 方法进行转换成其他  dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [54]:
#浮点数转换成整数，小数点后将被截取删除
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [55]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [57]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [58]:
#将全是表示数字的字符串数组，用astype转换成数值形式
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [61]:
#将一个数组的dtype转换成另一种数组的dtype的方法
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype=np.float)
int_array.astype(calibers.dtype)
#即便是astype前后的dtype相同，astype还是会创建出一个新的数组

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [62]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [63]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [64]:
arr*arr #并不是数组运算，而是数组对应的值相乘

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [65]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [66]:
arr**0.5 #不同大小的数组之间的运算叫广播

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [67]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]

5

In [69]:
arr[5:8]

array([5, 6, 7])

In [70]:
arr[5:8] = 12 #将对应位置的数值换成12，数组切片是原始视图，是在原数组上操作
arr #list则不同于数组

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [71]:
arr_slice = arr[5:8] #将arr中间部分赋值给arr_slice,但是并不是复制一份，而是原始切片
arr_slice[1] = 12345 #所以在对arr_slice进行赋值的时候才会改变arr中的值！！！！
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [72]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
#若想要得到ndarray切片的副本而不是原始视图，则需要进行复制操作
#例如：arr[5:8].copy()

In [74]:
#在一个二维数组，各索引位置上的元素不再是标量而是一维数组
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [75]:
arr2d[0][2]

3

In [76]:
arr2d[0,2]
#两种索引方式都可以

3

In [78]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0]#省略了后面的索引，返回一个第一维度的ndarray

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[1,0] #返回的都是视图，不是副本！！！！

array([7, 8, 9])

In [84]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2,1:]#在不同维度上切片

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[2,:1]

array([7])

In [89]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [91]:
arr2d[:2,1:]=0 #对切片的赋值会扩散到整个选区
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [97]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [98]:
data

array([[ 1.57023919,  0.68690571, -0.55670937,  0.17652122],
       [ 0.56967971, -0.6923248 ,  0.56791454,  0.93729104],
       [ 0.17754948,  1.09472924, -0.84061285, -1.40429841],
       [-1.14101062,  0.55325898, -0.35685514, -1.09013864],
       [-0.41460102, -0.83668382,  0.27116793,  0.88789352],
       [-0.02044686, -0.08625247, -0.20329233, -0.70143923],
       [-0.44847975, -2.04439892,  0.00897688, -0.84549334]])

In [99]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [102]:
data[names == 'Bob',2:] #布尔型数组的长度必须和被索引的轴长度一致，也可切片

array([[-0.55670937,  0.17652122],
       [-0.35685514, -1.09013864]])

In [103]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [105]:
data[~(names == 'Bob')] #python3以后翻转符号由-换成了~

array([[ 0.56967971, -0.6923248 ,  0.56791454,  0.93729104],
       [ 0.17754948,  1.09472924, -0.84061285, -1.40429841],
       [-0.41460102, -0.83668382,  0.27116793,  0.88789352],
       [-0.02044686, -0.08625247, -0.20329233, -0.70143923],
       [-0.44847975, -2.04439892,  0.00897688, -0.84549334]])

In [106]:
mask = (names == 'Bob') | (names == 'Will')
mask
#Python关键字and和or在布尔型数组中无效！！！要使用 &和|

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [107]:
data[mask]

array([[ 1.57023919,  0.68690571, -0.55670937,  0.17652122],
       [ 0.17754948,  1.09472924, -0.84061285, -1.40429841],
       [-1.14101062,  0.55325898, -0.35685514, -1.09013864],
       [-0.41460102, -0.83668382,  0.27116793,  0.88789352]])

In [108]:
data[data < 0] = 0 #将data中所有的负值设置成0
data

array([[ 1.57023919,  0.68690571,  0.        ,  0.17652122],
       [ 0.56967971,  0.        ,  0.56791454,  0.93729104],
       [ 0.17754948,  1.09472924,  0.        ,  0.        ],
       [ 0.        ,  0.55325898,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.27116793,  0.88789352],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00897688,  0.        ]])

In [110]:
data[names != 'Joe'] = 7 #通过一维布尔数组设置整行或列的值
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.56967971,  0.        ,  0.56791454,  0.93729104],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00897688,  0.        ]])

In [111]:
arr = np.empty((8,4)) #花式索引，利用整数数组进行索引
for i in range(8): #range(8)整数数组
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [115]:
arr[[4,3,0,6]]#以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [117]:
arr[[-3,-5,-7]]#负数索引将会从末尾开始选取行

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [118]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [121]:
arr[[1,5,7,2],[0,3,1,2]] #找到的是元素(1,0)、(5,3)、(7,1)、(2,2)
#而不是分别第1，5，7，2行的0，3，1，2位

array([[ 0,  3,  1,  2],
       [ 4,  7,  5,  6],
       [ 8, 11,  9, 10],
       [12, 15, 13, 14],
       [16, 19, 17, 18],
       [20, 23, 21, 22],
       [24, 27, 25, 26],
       [28, 31, 29, 30]])

In [120]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [123]:
#使用np.ix_函数，它可以将两个一维整数数组转换为一个用于选取方形区域的索引器
arr[np.ix_([1,5,7,2],[0,3,1,2])]
#花式索引和切片不一样，它总是将数据复制到新数组中

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [124]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
arr.T#进行转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [127]:
arr = np.random.randn(6,3)
np.dot(arr.T, arr)

array([[ 6.1586257 , -0.94219886,  2.34559712],
       [-0.94219886,  2.62943997,  0.13114022],
       [ 2.34559712,  0.13114022,  1.72387677]])

In [128]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [129]:
arr.transpose((1,0,2)) #https://blog.csdn.net/u012762410/article/details/78912667

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [131]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [132]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [133]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [134]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [137]:
x = np.random.randn(8)
x

array([ 0.27472021,  0.66843024, -0.68567587, -1.06420524, -0.66744908,
       -0.4725394 ,  0.99291518, -0.07588329])

In [136]:
y = np.random.randn(8)
y

array([ 0.65784945, -0.14009162, -0.32954894, -0.86137437,  0.73093819,
       -1.68438389,  0.56884507,  0.18980829])

In [138]:
np.maximum(x,y)#选择两个数组中较大的元素组成新的数组

array([ 0.65784945,  0.66843024, -0.32954894, -0.86137437,  0.73093819,
       -0.4725394 ,  0.99291518,  0.18980829])

In [140]:
arr = np.random.randn(7)*5
arr

array([ -1.76722967,  11.85285488,   1.39424119,   1.82602942,
        -1.8149666 ,   3.66412585,   3.73169331])

In [143]:
reminder,whole_part = np.modf(arr)
reminder

array([-0.76722967,  0.85285488,  0.39424119,  0.82602942, -0.8149666 ,
        0.66412585,  0.73169331])

In [144]:
whole_part

array([ -1.,  11.,   1.,   1.,  -1.,   3.,   3.])

In [147]:
points = np.arange(-5,5,0.01)
xs,ys = np.meshgrid(points,points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [152]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [154]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

In [155]:
plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2+y^2}$ for a grid of values')

In [157]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
           for x, y, c in zip (xarr,yarr,cond)]
result
#根据cond中的值选取xarr和yarr的值，当cond中的值为True时，选取xarr的值
#否则从yarr中选取

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [158]:
#上面过程的简化写法
#上面的缺点，1.对大数组的处理速度不够快 2.无法用于多维数组

result = np.where(cond,xarr,yarr)
result
#where的第二个和第三个参数不必是数组，它们都可以是标量值。
#where通常用于根据另一个数组而产生一个新的数组

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [159]:
#将整数替换为2，负数为-2
arr = np.random.randn(4,4)
arr

array([[ 0.19585544,  1.47748971, -1.32580979, -0.05564473],
       [ 0.94827305, -0.15863722, -1.31062811,  0.52748999],
       [-0.73545799,  0.84010361, -0.77692055,  0.45966732],
       [ 0.2368552 ,  1.35779696, -0.67094494,  0.22252104]])

In [160]:
np.where(arr>0,2,-2)

array([[ 2,  2, -2, -2],
       [ 2, -2, -2,  2],
       [-2,  2, -2,  2],
       [ 2,  2, -2,  2]])

In [161]:
np.where(arr>0,2,arr) #只将正值设置为2

array([[ 2.        ,  2.        , -1.32580979, -0.05564473],
       [ 2.        , -0.15863722, -1.31062811,  2.        ],
       [-0.73545799,  2.        , -0.77692055,  2.        ],
       [ 2.        ,  2.        , -0.67094494,  2.        ]])

In [162]:
result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
        
#可以改写为
np.where(cond1 & cond2 , 0,
                np.where(cond1,1,
                        np.where(cond2,2,3)))

###
result = 1 * (cond1 - cond2) + 2*(cond2& - cond1) +3* -(cond1|cond2)

NameError: name 'n' is not defined

In [165]:
arr = np.random.randn(5,4)
arr.mean()

-0.04411312948547523

In [166]:
np.mean(arr)

-0.04411312948547523

In [167]:
arr.sum()

-0.88226258970950455

In [168]:
arr.mean(axis=1)

array([-0.12325231,  0.46708633, -0.62276714,  0.10599803, -0.04763056])

In [169]:
arr.sum(0)

array([ 4.93962592,  0.60289276, -3.24152814, -3.18325312])

In [170]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr.cumsum(0)#所有元素的累计和

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [171]:
arr.cumprod(1)#所有元素的累计积

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [179]:
arr = np.random.randn(100)
# arr = np.array([1,2,3,4,5,-6])
arr
(arr>0).sum()#正值的数量

45

In [175]:
bools = np.array([False,False,True,False])
bools.any() #是否存在一个或多个True

True

In [176]:
bools.all()#是否检查数组中所有的值都是True

False

In [181]:
arr = np.random.randn(8)
arr

array([-0.91361361,  0.31216766, -1.41905116, -0.16628094,  1.4414997 ,
       -0.04179551,  0.54134927, -1.14306097])

In [182]:
arr.sort()
arr

array([-1.41905116, -1.14306097, -0.91361361, -0.16628094, -0.04179551,
        0.31216766,  0.54134927,  1.4414997 ])

In [183]:
arr = np.random.randn(5,3)
arr

array([[-2.14151761, -0.50859037,  0.32476633],
       [-0.36262098, -0.30029879,  1.05549823],
       [ 0.07347637, -0.06316893, -0.56314138],
       [-1.78786038,  1.34182381,  0.58703935],
       [-2.00464239,  0.01102771, -0.77834314]])

In [188]:
arr.sort(1) #对一个轴上的数据进行排序,就地排序，不返回值
arr
#np.sort()返回值
# w = np.sort(arr)
# print(w)

[[-2.14151761 -0.50859037  0.32476633]
 [-0.36262098 -0.30029879  1.05549823]
 [-0.56314138 -0.06316893  0.07347637]
 [-1.78786038  0.58703935  1.34182381]
 [-2.00464239 -0.77834314  0.01102771]]


In [190]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05* len(large_arr))] #5%分位数
#排完序后第5%位置的数

-1.6647784765276072

In [191]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [192]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [193]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [194]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [195]:
arr = np.arange(10)
np.save('some_array',arr)

In [196]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
np.savez('array_archive.npz',a=arr,b=arr)

In [198]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [201]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [202]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [203]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [204]:
from numpy.linalg import inv,qr
X = np.random.randn(5,5)
mat = X.T.dot(X)
inv(mat)

array([[ 2.97319982,  3.26349527,  1.99603474,  1.49649333,  0.33217326],
       [ 3.26349527,  4.94954282,  2.67105977,  1.91994198,  1.32907237],
       [ 1.99603474,  2.67105977,  1.59903661,  1.08642637,  0.57455603],
       [ 1.49649333,  1.91994198,  1.08642637,  0.96618667,  0.28837178],
       [ 0.33217326,  1.32907237,  0.57455603,  0.28837178,  1.17933267]])

In [205]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   3.61089900e-15,  -1.47639389e-15,
          7.01634000e-16,  -4.44089210e-16],
       [  1.93253828e-15,   1.00000000e+00,   2.73967422e-15,
          3.76037416e-16,   8.88178420e-16],
       [ -1.30014159e-15,  -1.75393542e-17,   1.00000000e+00,
         -5.70386004e-16,  -5.27355937e-16],
       [  2.03442071e-15,  -1.36080061e-15,  -2.91877540e-16,
          1.00000000e+00,  -2.22044605e-16],
       [ -8.88178420e-16,   1.33226763e-15,  -4.44089210e-16,
          8.88178420e-16,   1.00000000e+00]])

In [206]:
q,r =qr(mat)
r

array([[ -5.43897099,  -2.81514013,  10.06048257,   3.36287882,
         -1.21971728],
       [  0.        ,  -5.85613304,   6.07364463,   4.23496248,
          2.96610043],
       [  0.        ,   0.        ,  -4.40733331,   5.5527293 ,   0.8567938 ],
       [  0.        ,   0.        ,   0.        ,  -0.56626198,
          0.66024016],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.52122436]])

In [207]:
q

array([[-0.64990311,  0.33459553, -0.20296408, -0.62809315,  0.1731368 ],
       [ 0.02387724, -0.68906903,  0.02740832, -0.20968319,  0.6927449 ],
       [ 0.6640216 ,  0.3750645 , -0.52257973, -0.23585698,  0.2994726 ],
       [ 0.2831207 ,  0.30223599,  0.82380507, -0.35672015,  0.1503064 ],
       [-0.23658784,  0.42568736,  0.07943543,  0.61534882,  0.61469692]])

In [209]:
samples = np.random.normal(size = (4,4))
samples

array([[ 1.49947697,  0.41209447, -0.25340622,  0.86297279],
       [-0.01631151, -0.41014938, -1.14290669, -0.15530636],
       [ 0.54395667, -0.34017148, -0.06703546,  0.39725527],
       [ 2.11650201, -0.0622779 , -1.30152513,  0.43736769]])

In [213]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0,1) for _ in range(N)]

996 ms ± 43.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [214]:
%timeit np.random.normal(size=N)

45 ms ± 1.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [215]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1000
    position += steps
    walk.append(position)

In [216]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()

In [217]:
walk.min()

-12

In [218]:
walk.max()

18

In [219]:
(np.abs(walk) >= 10).argmax()

177

In [220]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws>0,1,-1)
walks = steps.cumsum(1)

In [221]:
walks

array([[ -1,  -2,  -1, ..., -36, -37, -36],
       [ -1,  -2,  -1, ..., -16, -17, -16],
       [ -1,   0,   1, ..., -36, -37, -38],
       ..., 
       [  1,   2,   3, ...,  76,  75,  74],
       [  1,   2,   1, ...,  22,  21,  20],
       [  1,   0,   1, ...,   4,   3,   4]])

In [222]:
walks.max()

132

In [223]:
walks.min()

-115

In [224]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([ True,  True,  True, ...,  True, False, False], dtype=bool)

In [225]:
hits30.sum()

3375

In [226]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

499.80829629629631

In [227]:
steps = np.random.normal(loc=0,scale=0.25,
                         size=(nwalks,nsteps))